name: AL CI-CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install BC Helper
        shell: pwsh
        run: |
          Install-Module BcContainerHelper -Force -AllowClobber -Scope CurrentUser
          Import-Module BcContainerHelper

      - name: Get BC Artifact
        shell: pwsh
        run: |
          $artifactUrl = Get-BcArtifactUrl -type Sandbox -country w1 -select Latest
          echo "ARTIFACT_URL=$artifactUrl" >> $env:GITHUB_ENV

      - name: Create Output Folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE/output" -Force

      - name: Create Container
        shell: pwsh
        run: |
          $credential = New-Object pscredential ('admin',(ConvertTo-SecureString 'P@ssword1' -AsPlainText -Force))

          New-BcContainer `
            -accept_eula `
            -artifactUrl $env:ARTIFACT_URL `
            -containerName bcbuild `
            -auth UserPassword `
            -Credential $credential `
            -updateHosts `
            -dockerVolumes @(
              "${env:GITHUB_WORKSPACE}:C:\Sources"
            )

      - name: Compile AL
        shell: pwsh
        run: |
          $credential = New-Object pscredential ('admin',(ConvertTo-SecureString 'P@ssword1' -AsPlainText -Force))

          Compile-AppInBcContainer `
            -containerName bcbuild `
            -credential $credential `
            -appProjectFolder "C:\Sources" `
            -appOutputFolder "C:\Sources\output"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: al-app
          path: output/*.app

      - name: Cleanup Container
        if: always()
        shell: pwsh
        run: |
          Remove-BcContainer -containerName bcbuild -force